### ISSUE TITLE
/queueadmin is broken

### ISSUE THREAD

**Issue by 8CTN8** [CTN-Originals/HeatseekerHeaven-DiscordBot#11]
```js
CTN#3460 in #beta-ranked-3v3 triggered an interaction.
0|heatseeker-heaven-bot  | /queueadmin undo
0|heatseeker-heaven-bot  | gameid:136
0|heatseeker-heaven-bot  | Error: Cannot read properties of null (reading 'id')
0|heatseeker-heaven-bot  | TypeError: Cannot read properties of null (reading 'id')
0|heatseeker-heaven-bot  |     at Object.execute (/root/discord-bots/heatseeker-heaven-bot/commands/queueAdmin.js:181:110)
0|heatseeker-heaven-bot  |     at runMicrotasks (<anonymous>)
0|heatseeker-heaven-bot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|heatseeker-heaven-bot  |     at async executeCommand (/root/discord-bots/heatseeker-heaven-bot/index.js:86:3)
```

**Comment by 8CTN8** [comment]
```js
CTN#3460 in #beta-ranked-3v3 triggered an interaction.
0|heatseeker-heaven-bot  | /queueadmin substitute
0|heatseeker-heaven-bot  | gameid:143 replacing:985720411729829890 replaced-by:287657356312051724
0|heatseeker-heaven-bot  | Error: Cannot read properties of null (reading 'id')
0|heatseeker-heaven-bot  | TypeError: Cannot read properties of null (reading 'id')
0|heatseeker-heaven-bot  |     at Object.execute (/root/discord-bots/heatseeker-heaven-bot/commands/queueAdmin.js:181:110)
```

**Comment by 8CTN8** [comment]
fixed in beta_0.0.4
