### ISSUE TITLE
Inactive users in queue dont get removed

### ISSUE THREAD

**Issue by 8CTN8** [CTN-Originals/HeatseekerHeaven-DiscordBot#27]
```js
TypeError: Cannot read properties of null (reading 'user')
  at getCommandPermissions (/root/discord-bots/heatseeker-heaven-bot/utils/userPermissions.js:50:66)
  at Object.execute (/root/discord-bots/heatseeker-heaven-bot/commands/queueAdmin.js:161:34)
  at Object.queueInactivityTimeout (/root/discord-bots/heatseeker-heaven-bot/data/queueData.js:330:20)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by 8CTN8** [comment]
Fixed in `beta-dev_0.1.2_general-bugfixes`
